package com.hibernate.jdbc.demo;

import javax.persistence.GeneratedValue;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

import com.hibernate.jdbc.entity.Student;

public class PrimaryKeyDemo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		SessionFactory sessionFactory = new Configuration().configure("hibernate.cfg.xml")
				.addAnnotatedClass(Student.class).buildSessionFactory();
		Session session = sessionFactory.getCurrentSession();
		try {
			Student student = new Student("tonmoy", "saha", "tonmoy@gmail.com");
			Student student2 = new Student("piki", "saha", "piki@gmail.com");
			Student student3 = new Student("dipa", "saha", "dipa@gmail.com");

			session.beginTransaction();
			// primary key autogenerated by hibernate @Id and @GeneratedValue
			// annotation type
			session.save(student);
			session.save(student2);
			session.save(student3);

			session.getTransaction().commit();
		} finally {
			sessionFactory.close();
		}

	}

}
